### PR TITLE
Damaged Water Bottle Scrap

### PR DESCRIPTION
**Pull request by BastedEggsRYummy**
Based off of model by @Christian2147

### CODE REVIEW

**Review by marinocj — CHANGES_REQUESTED** [review]
This PR needs to be remade so it does not delete all of the files from other people.

**Comment by BastedEggsRYummy** [comment]
Pretty sure it's all fixed now. Thanks for the heads up

**Review by maryellenmarino — APPROVED** [review]
Looks good to me! Love the detail. Nice catch @marinocj on the deleted files. @BastedEggsRYummy after you make a PR, you can go into the "Files Changed" tab and make sure you aren't making any unintended changes.

**Review by maryellenmarino — APPROVED** [review]

**Review by marinocj — APPROVED** [review]
Looks great. Thank you for fixing that issue with the files being deleted.

**Pull request merged**
